// Copyright (C) 2026 Shingo Hirano and Sho Higashi
// Licensed under the MIT found in the
// https://github.com/astro-sim-lab/arche/blob/main/LICENSE
#pragma once
// ---------------------------------------------------------------------------
// species_composition.h — nuclear composition and charge of catalog species.
//
// The catalog (core/species_catalog.h) carries each species' display name and
// mass.  This header adds what a conservation law needs: how many nuclei of
// each tracked element the species contains, and its charge in units of e.
//
// Scope: ALL 89 catalog species (SpId::H .. SpId::CH4_p), over nine elements.
// A species outside the catalog has no registered composition, and every
// consumer must treat "unknown" as "do not assume" rather than "zero" —
// composition_of() says which.
// The scope is the whole catalog, not just the primordial block, so that the
// conservation projection reaches metal_grain as well as the zero-metal
// networks.
//
// D is a tracked element in its own right, not a hydrogen isotope: no reaction
// in either primordial network converts D into H, so y_D + y_HD + y_D+ (+...)
// is conserved separately from the H total.  Keeping them separate is what
// makes the deuterium budget checkable at all.
//
// The table is not trusted blindly.  solve/conservation.h re-derives each
// loaded reaction's element/charge balance from it and refuses to build an
// invariant matrix if any reaction fails to balance, so a typo here disables
// the conservation projection instead of enforcing a wrong law.
// ---------------------------------------------------------------------------
#include <array>
#include <iterator>  // std::size

#include "core/species_catalog.h"

namespace arche {
namespace composition {

//: Elements tracked for conservation, in the order of Composition::n.
//: ⚠ The four primordial elements come FIRST and in their original order.  An
//: invariant matrix emits one row per element in this order and prunes the
//: all-zero ones (solve/conservation.h), so appending the five metal elements
//: leaves the primordial models with exactly the rows {H, He, D, Li, charge}
//: they carried before, in the same order.  Inserting a metal element before Li
//: would reorder those rows and move the least-squares rounding.
//: ⓘ These nine are exhaustive for the shipped catalog: no species in it
//: contains Si, Fe, S or N (measured — all 89 names parse with these alone,
//: tools/python/derive_composition.py).
inline constexpr int kNElements = 9;
inline constexpr std::array<const char*, kNElements> kElementNames = {
    {"H", "He", "D", "Li", "C", "O", "K", "Na", "Mg"}};

//: Upper bound on the number of invariant rows any model can carry: one row per
//: tracked element, plus one for charge.  Single source of truth for three
//: sizes that must agree — ReactionTable::invariants (kinetics/topology.h),
//: ChemCell::cons_carry and conservation::kMaxRows (solve/conservation.h).
inline constexpr int kMaxInvariantRows = kNElements + 1;

// Nuclei per element plus charge [e].  `known == false` marks a species with no
// registered composition; its `n`/`q` must not be read.
struct Composition {
  std::array<int, kNElements> n{};  // nuclei, in kElementNames order
  int q = 0;                        // charge [e]
  bool known = false;
};

namespace detail {

struct Row {
  SpId id;
  std::array<int, kNElements> n;
  int q;
};

//: Composition of every catalog species, one row per SpId from SpId::H to
//: SpId::CH4_p.  ⚠ GENERATED, not hand-typed: the formulae are read off the
//: display names in core/species_catalog.h by
//: tools/python/derive_composition.py, which cross-checks
//: each one against the mass column of that same file.  A mis-parse therefore
//: surfaces as a mass mismatch rather than as a silently wrong conservation
//: law.  Regenerate with `--emit-cxx` after any catalog change.
//: ⓘ Grain charge states (Gr, Gr+, Gr2+, Gr-, Gr2-) carry charge but none of
//: the tracked elements; the `_p` / `_c` suffixes mark the ice mantle and the
//: chemisorbed phase, which is WHERE a species sits and not what it is made of,
//: so they are not read as elements.  D is counted as its own element, never
//: as H.
// clang-format off
inline constexpr Row kCatalog[] = {
    // Generated by derive_composition.py from species_catalog.h; do not edit by hand.
    // 89 rows = SpId::Count, in SpId order.  Columns: {H, He, D, Li, C, O, K, Na, Mg}, charge.
    {SpId::H, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 0},  // H
    {SpId::H2, {2, 0, 0, 0, 0, 0, 0, 0, 0}, 0},  // H2
    {SpId::e, {0, 0, 0, 0, 0, 0, 0, 0, 0}, -1},  // e
    {SpId::Hp, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 1},  // H+
    {SpId::H2p, {2, 0, 0, 0, 0, 0, 0, 0, 0}, 1},  // H2+
    {SpId::H3p, {3, 0, 0, 0, 0, 0, 0, 0, 0}, 1},  // H3+
    {SpId::Hm, {1, 0, 0, 0, 0, 0, 0, 0, 0}, -1},  // H-
    {SpId::He, {0, 1, 0, 0, 0, 0, 0, 0, 0}, 0},  // He
    {SpId::Hep, {0, 1, 0, 0, 0, 0, 0, 0, 0}, 1},  // He+
    {SpId::Hepp, {0, 1, 0, 0, 0, 0, 0, 0, 0}, 2},  // He++
    {SpId::HeHp, {1, 1, 0, 0, 0, 0, 0, 0, 0}, 1},  // HeH+
    {SpId::D, {0, 0, 1, 0, 0, 0, 0, 0, 0}, 0},  // D
    {SpId::HD, {1, 0, 1, 0, 0, 0, 0, 0, 0}, 0},  // HD
    {SpId::Dp, {0, 0, 1, 0, 0, 0, 0, 0, 0}, 1},  // D+
    {SpId::HDp, {1, 0, 1, 0, 0, 0, 0, 0, 0}, 1},  // HD+
    {SpId::Dm, {0, 0, 1, 0, 0, 0, 0, 0, 0}, -1},  // D-
    {SpId::Li, {0, 0, 0, 1, 0, 0, 0, 0, 0}, 0},  // Li
    {SpId::LiH, {1, 0, 0, 1, 0, 0, 0, 0, 0}, 0},  // LiH
    {SpId::Lip, {0, 0, 0, 1, 0, 0, 0, 0, 0}, 1},  // Li+
    {SpId::Lim, {0, 0, 0, 1, 0, 0, 0, 0, 0}, -1},  // Li-
    {SpId::LiHp, {1, 0, 0, 1, 0, 0, 0, 0, 0}, 1},  // LiH+
    {SpId::Lipp, {0, 0, 0, 1, 0, 0, 0, 0, 0}, 2},  // Li++
    {SpId::Lippp, {0, 0, 0, 1, 0, 0, 0, 0, 0}, 3},  // Li+++
    {SpId::C, {0, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // C
    {SpId::C2, {0, 0, 0, 0, 2, 0, 0, 0, 0}, 0},  // C2
    {SpId::CH, {1, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH
    {SpId::CH2, {2, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH2
    {SpId::CH3, {3, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH3
    {SpId::CH4, {4, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH4
    {SpId::Cp, {0, 0, 0, 0, 1, 0, 0, 0, 0}, 1},  // C+
    {SpId::C2p, {0, 0, 0, 0, 2, 0, 0, 0, 0}, 1},  // C2+
    {SpId::CHp, {1, 0, 0, 0, 1, 0, 0, 0, 0}, 1},  // CH+
    {SpId::CH2p, {2, 0, 0, 0, 1, 0, 0, 0, 0}, 1},  // CH2+
    {SpId::CH3p, {3, 0, 0, 0, 1, 0, 0, 0, 0}, 1},  // CH3+
    {SpId::CH4p, {4, 0, 0, 0, 1, 0, 0, 0, 0}, 1},  // CH4+
    {SpId::CH5p, {5, 0, 0, 0, 1, 0, 0, 0, 0}, 1},  // CH5+
    {SpId::O, {0, 0, 0, 0, 0, 1, 0, 0, 0}, 0},  // O
    {SpId::O2, {0, 0, 0, 0, 0, 2, 0, 0, 0}, 0},  // O2
    {SpId::OH, {1, 0, 0, 0, 0, 1, 0, 0, 0}, 0},  // OH
    {SpId::CO, {0, 0, 0, 0, 1, 1, 0, 0, 0}, 0},  // CO
    {SpId::H2O, {2, 0, 0, 0, 0, 1, 0, 0, 0}, 0},  // H2O
    {SpId::HCO, {1, 0, 0, 0, 1, 1, 0, 0, 0}, 0},  // HCO
    {SpId::O2H, {1, 0, 0, 0, 0, 2, 0, 0, 0}, 0},  // O2H
    {SpId::CO2, {0, 0, 0, 0, 1, 2, 0, 0, 0}, 0},  // CO2
    {SpId::H2CO, {2, 0, 0, 0, 1, 1, 0, 0, 0}, 0},  // H2CO
    {SpId::H2O2, {2, 0, 0, 0, 0, 2, 0, 0, 0}, 0},  // H2O2
    {SpId::Op, {0, 0, 0, 0, 0, 1, 0, 0, 0}, 1},  // O+
    {SpId::O2p, {0, 0, 0, 0, 0, 2, 0, 0, 0}, 1},  // O2+
    {SpId::OHp, {1, 0, 0, 0, 0, 1, 0, 0, 0}, 1},  // OH+
    {SpId::COp, {0, 0, 0, 0, 1, 1, 0, 0, 0}, 1},  // CO+
    {SpId::H2Op, {2, 0, 0, 0, 0, 1, 0, 0, 0}, 1},  // H2O+
    {SpId::HCOp, {1, 0, 0, 0, 1, 1, 0, 0, 0}, 1},  // HCO+
    {SpId::O2Hp, {1, 0, 0, 0, 0, 2, 0, 0, 0}, 1},  // O2H+
    {SpId::H3Op, {3, 0, 0, 0, 0, 1, 0, 0, 0}, 1},  // H3O+
    {SpId::H2COp, {2, 0, 0, 0, 1, 1, 0, 0, 0}, 1},  // H2CO+
    {SpId::HOCOp, {1, 0, 0, 0, 1, 2, 0, 0, 0}, 1},  // HOCO+
    {SpId::H2COHp, {3, 0, 0, 0, 1, 1, 0, 0, 0}, 1},  // H2COH+
    {SpId::K, {0, 0, 0, 0, 0, 0, 1, 0, 0}, 0},  // K
    {SpId::Kp, {0, 0, 0, 0, 0, 0, 1, 0, 0}, 1},  // K+
    {SpId::Na, {0, 0, 0, 0, 0, 0, 0, 1, 0}, 0},  // Na
    {SpId::Nap, {0, 0, 0, 0, 0, 0, 0, 1, 0}, 1},  // Na+
    {SpId::Mg, {0, 0, 0, 0, 0, 0, 0, 0, 1}, 0},  // Mg
    {SpId::Mgp, {0, 0, 0, 0, 0, 0, 0, 0, 1}, 1},  // Mg+
    {SpId::Gr, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 0},  // Gr
    {SpId::Grp, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 1},  // Gr+
    {SpId::Gr2p, {0, 0, 0, 0, 0, 0, 0, 0, 0}, 2},  // Gr2+
    {SpId::Grm, {0, 0, 0, 0, 0, 0, 0, 0, 0}, -1},  // Gr-
    {SpId::Gr2m, {0, 0, 0, 0, 0, 0, 0, 0, 0}, -2},  // Gr2-
    {SpId::H_p, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 0},  // H_p
    {SpId::H_c, {1, 0, 0, 0, 0, 0, 0, 0, 0}, 0},  // H_c
    {SpId::H2_p, {2, 0, 0, 0, 0, 0, 0, 0, 0}, 0},  // H2_p
    {SpId::D_p, {0, 0, 1, 0, 0, 0, 0, 0, 0}, 0},  // D_p
    {SpId::D_c, {0, 0, 1, 0, 0, 0, 0, 0, 0}, 0},  // D_c
    {SpId::HD_p, {1, 0, 1, 0, 0, 0, 0, 0, 0}, 0},  // HD_p
    {SpId::O_p, {0, 0, 0, 0, 0, 1, 0, 0, 0}, 0},  // O_p
    {SpId::O2_p, {0, 0, 0, 0, 0, 2, 0, 0, 0}, 0},  // O2_p
    {SpId::OH_p, {1, 0, 0, 0, 0, 1, 0, 0, 0}, 0},  // OH_p
    {SpId::CO_p, {0, 0, 0, 0, 1, 1, 0, 0, 0}, 0},  // CO_p
    {SpId::CO2_p, {0, 0, 0, 0, 1, 2, 0, 0, 0}, 0},  // CO2_p
    {SpId::H2O_p, {2, 0, 0, 0, 0, 1, 0, 0, 0}, 0},  // H2O_p
    {SpId::HO2_p, {1, 0, 0, 0, 0, 2, 0, 0, 0}, 0},  // HO2_p
    {SpId::H2O2_p, {2, 0, 0, 0, 0, 2, 0, 0, 0}, 0},  // H2O2_p
    {SpId::HCO_p, {1, 0, 0, 0, 1, 1, 0, 0, 0}, 0},  // HCO_p
    {SpId::H2CO_p, {2, 0, 0, 0, 1, 1, 0, 0, 0}, 0},  // H2CO_p
    {SpId::C_p, {0, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // C_p
    {SpId::CH_p, {1, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH_p
    {SpId::CH2_p, {2, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH2_p
    {SpId::CH3_p, {3, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH3_p
    {SpId::CH4_p, {4, 0, 0, 0, 1, 0, 0, 0, 0}, 0},  // CH4_p
};
// clang-format on

// One row per catalog species, no more and no less.  Without this a species
// added to species_catalog.h but not here would fail CLOSED at run time
// (composition_of() returns known == false, build_invariants() returns 0, the
// projection silently stops for that whole network) -- safe, but silent.  Fail
// at compile time instead.  Mirrors the same guard on kSpeciesCatalog
// (core/species_catalog.h).
static_assert(std::size(kCatalog) == static_cast<std::size_t>(SpId::Count),
              "kCatalog must have exactly one row per SpId; regenerate it with "
              "tools/python/derive_composition.py --emit-cxx");

}  // namespace detail

// ---------------------------------------------------------------------------
// composition_of — registered composition of one catalog species.
//   `.known == false` only for an id outside the catalog.  build_invariants()
//   fails the whole matrix closed on the first unknown species, so adding a
//   species to the catalog without adding it here disables the projection for
//   that network rather than asserting a wrong law.
// ---------------------------------------------------------------------------
inline constexpr Composition composition_of(SpId id) {
  for (const detail::Row& r : detail::kCatalog) {
    if (r.id == id) return Composition{r.n, r.q, true};
  }
  return Composition{};
}

}  // namespace composition
}  // namespace arche
