#!/usr/bin/env python3
# Copyright (C) 2026 Shingo Hirano and Sho Higashi
# Licensed under the MIT found in the
# https://github.com/astro-sim-lab/arche/blob/main/LICENSE
"""Derive the per-species element/charge composition of the metal_grain catalog.

The composition is NOT hand-typed: it is parsed from the display names in
`src/include/core/species_catalog.h`, then cross-checked against the masses
tabulated in the same file.  A parse error therefore shows up as a mass
mismatch rather than as a silently wrong conservation law.

Run from the repository root:  python3 <this file>
"""
from __future__ import annotations

import pathlib
import re
import sys
from typing import Final

CATALOG: Final = pathlib.Path("src/include/core/species_catalog.h")

#: Elements tracked for conservation.  Longest symbol first so the greedy
#: formula scan cannot mistake "Na" for "N"+"a" or "He" for "H"+"e".
ELEMENTS: Final[tuple[str, ...]] = ("He", "Li", "Na", "Mg", "H", "D", "C", "O", "K")

#: Storage order of `Composition::n` in core/species_composition.h.
#: ⚠ The four primordial elements come FIRST and in their original order.  The
#: rows of an invariant matrix are emitted in this order and all-zero rows are
#: pruned (solve/conservation.h), so appending the metal elements leaves the
#: primordial models with exactly the rows {H, He, D, Li, charge} they had
#: before, in the same order — which is what keeps their output unchanged.
#: Inserting a metal element before Li would reorder those rows and move the
#: least-squares rounding.
STORAGE_ORDER: Final[tuple[str, ...]] = (
    "H", "He", "D", "Li", "C", "O", "K", "Na", "Mg")

#: Two thresholds, not one, because the catalog's mass column mixes two error
#: scales.  Measured on all 89 rows: the largest deviation attributable to the
#: catalog's own rounding is 1.5e-3 amu (He++, tabulated as exactly 4.0), while
#: a genuine mis-parse — dropping an H, reading "Na" as N+a — moves the mass by
#: ~1 amu or more.  A single 5e-5 tolerance could not tell them apart and made
#: this audit exit non-zero on a correct table, which is worse than useless as a
#: gate.  So: report anything above ROUNDING_TOL, but FAIL only above PARSE_TOL.
ROUNDING_TOL: Final[float] = 5.0e-5   # report (catalog rounding lives here)
PARSE_TOL: Final[float] = 0.5         # fail (a mis-parse cannot be this small)

ROW_RE: Final = re.compile(r'\{SpId::(\w+),\s*"([^"]+)",\s*([0-9.]+)\}')
CHARGE_RE: Final = re.compile(r"([+-]+)$")
TERM_RE: Final = re.compile(r"([A-Z][a-z]?)(\d*)")


def read_catalog() -> list[tuple[str, str, float]]:
    rows = ROW_RE.findall(CATALOG.read_text())
    return [(sid, name, float(mass)) for sid, name, mass in rows]


def parse(name: str) -> tuple[dict[str, int], int] | None:
    """Return ({element: count}, charge) or None if the name is not parseable."""
    body = name
    # Phase suffix: `_p` = ice mantle / grain surface, `_c` = chemisorbed.
    # It marks WHERE the species sits, not what it is made of.
    if body.endswith(("_p", "_c")):
        body = body[:-2]
    # Dust grains carry charge but none of the tracked elements.
    if body.startswith("Gr"):
        rest = body[2:]
        if rest == "":
            return {}, 0
        m = re.fullmatch(r"(\d*)([+-])", rest)
        if m is None:
            return None
        n = int(m.group(1) or "1")
        return {}, n if m.group(2) == "+" else -n
    charge = 0
    m = CHARGE_RE.search(body)
    if m is not None:
        signs = m.group(1)
        charge = signs.count("+") - signs.count("-")
        body = body[: m.start()]
    if body == "e":
        # The electron is written without a sign in the catalog.
        return {}, -1
    comp: dict[str, int] = {}
    pos = 0
    while pos < len(body):
        for el in ELEMENTS:
            if body.startswith(el, pos):
                pos += len(el)
                m2 = re.match(r"\d*", body[pos:])
                digits = m2.group(0) if m2 else ""
                pos += len(digits)
                comp[el] = comp.get(el, 0) + int(digits or "1")
                break
        else:
            return None
    return comp, charge


def emit_cxx() -> int:
    """Print the detail::Row table for core/species_composition.h.

    The table is generated, never hand-typed: a mis-parse shows up as a mass
    mismatch in the audit above rather than as a silently wrong conservation
    law.
    """
    rows = read_catalog()
    if sorted(STORAGE_ORDER) != sorted(ELEMENTS):
        raise SystemExit("STORAGE_ORDER and ELEMENTS disagree")
    print(f"    // Generated by {pathlib.Path(__file__).name} from "
          f"{CATALOG.name}; do not edit by hand.")
    print(f"    // {len(rows)} rows = SpId::Count, in SpId order.  Columns: "
          f"{{{', '.join(STORAGE_ORDER)}}}, charge.")
    for sid, name, _mass in rows:
        r = parse(name)
        if r is None:
            raise SystemExit(f"species '{name}' (SpId::{sid}) is not parseable")
        comp, q = r
        counts = ", ".join(f"{comp.get(el, 0)}" for el in STORAGE_ORDER)
        print(f"    {{SpId::{sid}, {{{counts}}}, {q}}},  // {name}")
    return 0


def main() -> int:
    rows = read_catalog()
    by_name = {name: mass for _, name, mass in rows}
    m_e = by_name["e"]
    atom_mass = {el: by_name[el] for el in ELEMENTS}

    bad_parse: list[str] = []
    bad_mass: list[tuple[str, float, float]] = []
    parsed = 0
    for _sid, name, mass in rows:
        if name.startswith("Gr"):
            continue  # mass is a placeholder (1e6), no cross-check possible
        r = parse(name)
        if r is None:
            bad_parse.append(name)
            continue
        comp, q = r
        parsed += 1
        want = sum(atom_mass[el] * n for el, n in comp.items()) - q * m_e
        if abs(want - mass) > ROUNDING_TOL:
            bad_mass.append((name, mass, want))

    prim_names = {n for _s, n, _m in rows[:23]}
    metal_bad = [b for b in bad_mass if b[0] not in prim_names]
    prim_bad = [b for b in bad_mass if b[0] in prim_names]
    print(f"catalog rows           : {len(rows)}")
    print(f"parsed (excl. grains)  : {parsed}")
    print(f"parse failures         : {len(bad_parse)} {bad_parse}")
    print(f"mass mismatch, metal   : {len(metal_bad)}")
    for name, tab, calc in metal_bad:
        print(f"   {name:10s} catalog={tab:.5f} formula={calc:.5f} d={calc - tab:+.2e}")
    print(f"mass mismatch, prim    : {len(prim_bad)}  (catalog rounding, see below)")
    for name, tab, calc in prim_bad:
        print(f"   {name:10s} catalog={tab:.5f} formula={calc:.5f} d={calc - tab:+.2e}")
    gross = [b for b in bad_mass if abs(b[2] - b[1]) > PARSE_TOL]
    print(f"mass mismatch > {PARSE_TOL} amu : {len(gross)}  "
          f"(a mis-parse would land here; catalog rounding cannot)")
    for name, tab, calc in gross:
        print(f"   {name:10s} catalog={tab:.5f} formula={calc:.5f} d={calc - tab:+.2e}")
    return 1 if (bad_parse or gross) else 0


if __name__ == "__main__":
    if "--emit-cxx" in sys.argv:
        sys.exit(emit_cxx())
    sys.exit(main())
